"""initial schema

Revision ID: 0001
Revises: (none)
Create Date: 2026-09-26 18:53:01.224498
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_call",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=50), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingredient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("density_g_per_ml", sa.Float(), nullable=True),
        sa.Column("default_unit", sa.String(length=40), nullable=True),
        sa.Column("shelf_life_days", sa.Integer(), nullable=True),
        sa.Column("pack_size", sa.Float(), nullable=True),
        sa.Column("pack_unit", sa.String(length=40), nullable=True),
        sa.Column("is_staple", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_name"),
    )
    op.create_table(
        "preference",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "prep_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("component_ids", sa.JSON(), nullable=False),
        sa.Column("tasks", sa.JSON(), nullable=False),
        sa.Column("est_minutes", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "recipe_family",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("preferred_recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["preferred_recipe_id"],
            ["recipe.id"],
            name="fk_family_preferred_recipe",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "shopping_list",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("week_start"),
    )
    op.create_table(
        "inventory_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column(
            "location",
            sa.Enum("fridge", "freezer", "pantry", name="location", native_enum=False),
            nullable=False,
        ),
        sa.Column("added_on", sa.Date(), nullable=False),
        sa.Column("best_by", sa.Date(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "photo",
                "receipt",
                "manual",
                "consumed-by-plan",
                "prep-yield",
                name="inventorysource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipe",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ref", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("servings", sa.Float(), nullable=True),
        sa.Column("prep_minutes", sa.Integer(), nullable=True),
        sa.Column("cook_minutes", sa.Integer(), nullable=True),
        sa.Column("total_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "meal_role",
            sa.Enum(
                "breakfast",
                "lunch",
                "dinner",
                "soup",
                "side",
                "bread",
                "dessert",
                "condiment",
                "snack",
                name="mealrole",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "approved", name="recipestatus", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "collection",
            sa.Enum("core", "discovered", name="collection", native_enum=False),
            nullable=False,
        ),
        sa.Column("family_id", sa.Integer(), nullable=True),
        sa.Column("pinned_favorite", sa.Boolean(), nullable=False),
        sa.Column("household_notes", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["recipe_family.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ref"),
    )
    op.create_table(
        "shopping_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shopping_list_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("qty_needed", sa.Float(), nullable=False),
        sa.Column("qty_on_hand", sa.Float(), nullable=False),
        sa.Column("qty_to_buy", sa.Float(), nullable=False),
        sa.Column("pack_size", sa.Float(), nullable=True),
        sa.Column("section", sa.String(length=100), nullable=False),
        sa.Column("retailer_sku", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.ForeignKeyConstraint(["shopping_list_id"], ["shopping_list.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sku_match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("retailer", sa.String(length=50), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("retailer", "ingredient_id"),
    )
    op.create_table(
        "component",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("yield_qty", sa.Float(), nullable=True),
        sa.Column("yield_unit", sa.String(length=40), nullable=True),
        sa.Column(
            "storage",
            sa.Enum("fridge", "freezer", "pantry", name="location", native_enum=False),
            nullable=False,
        ),
        sa.Column("keeps_days", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meal_slot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "meal", sa.Enum("lunch", "dinner", name="meal", native_enum=False), nullable=False
        ),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("component_ids", sa.JSON(), nullable=False),
        sa.Column("servings", sa.Float(), nullable=False),
        sa.Column("is_leftover_of", sa.Integer(), nullable=True),
        sa.Column("is_override", sa.Boolean(), nullable=False),
        sa.Column("cooked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["is_leftover_of"],
            ["meal_slot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date", "meal"),
    )
    op.create_table(
        "rating",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("would_repeat", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipe.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipe_ingredient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=True),
        sa.Column("qty", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=40), nullable=True),
        sa.Column("prep_note", sa.String(length=300), nullable=False),
        sa.Column("optional", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipe.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipe_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("pdf", "url", "photo", "manual", name="sourcekind", native_enum=False),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("file", sa.String(length=300), nullable=False),
        sa.Column("pages", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipe.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "step",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("equipment", sa.JSON(), nullable=False),
        sa.Column("active_minutes", sa.Integer(), nullable=False),
        sa.Column("passive_minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipe.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("step")
    op.drop_table("recipe_source")
    op.drop_table("recipe_ingredient")
    op.drop_table("rating")
    op.drop_table("meal_slot")
    op.drop_table("component")
    op.drop_table("sku_match")
    op.drop_table("shopping_line")
    op.drop_table("recipe")
    op.drop_table("inventory_item")
    op.drop_table("shopping_list")
    op.drop_table("recipe_family")
    op.drop_table("prep_session")
    op.drop_table("preference")
    op.drop_table("ingredient")
    op.drop_table("agent_call")
    # ### end Alembic commands ###
