"""ingredient match method

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 19:07:18.701384
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_ingredient", schema=None) as batch_op:
        batch_op.add_column(sa.Column("match_method", sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_ingredient", schema=None) as batch_op:
        batch_op.drop_column("match_method")

    # ### end Alembic commands ###
