"""week plan and prep components

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-26 20:41:49.718802
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "week_plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("conflicts", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("week_start"),
    )
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("kind", sa.String(length=30), nullable=False, server_default="main")
        )
        batch_op.add_column(
            sa.Column("freezer_ok", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column("active_minutes", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("passive_minutes", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("equipment", sa.JSON(), nullable=False, server_default="[]"))
        batch_op.add_column(
            sa.Column("per_serving", sa.JSON(), nullable=False, server_default="[]")
        )
        batch_op.create_unique_constraint("uq_component_name", ["name"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint("uq_component_name", type_="unique")
        batch_op.drop_column("per_serving")
        batch_op.drop_column("equipment")
        batch_op.drop_column("passive_minutes")
        batch_op.drop_column("active_minutes")
        batch_op.drop_column("freezer_ok")
        batch_op.drop_column("kind")

    op.drop_table("week_plan")
    # ### end Alembic commands ###
