"""shopping line details

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-26 21:07:22.460526
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shopping_line", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("name", sa.String(length=300), nullable=False, server_default="")
        )
        batch_op.add_column(sa.Column("pack_unit", sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column("packs", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("note", sa.Text(), nullable=False, server_default=""))
        batch_op.alter_column("ingredient_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shopping_line", schema=None) as batch_op:
        batch_op.alter_column("ingredient_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("note")
        batch_op.drop_column("packs")
        batch_op.drop_column("pack_unit")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
